#image: node:10.15.3


pipelines:

  branches:
    experimental:               # Exp deploy
      - step:
         name: Deploy EXP to new US site
         script:
           - echo $hardCodedOverrideConfig > app/js/Overridecore.js
           - sed -i -e  "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" -e "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" -e "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" app/js/Overridecore.js
           - tail -n +2 app/js/core.js >> app/js/Overridecore.js
           - mv app/js/Overridecore.js app/js/core.js
#           - sed -i "s/%CSSFILES%/$CSSFILES/" app/js/core.js

           - pipe: atlassian/rsync-deploy:0.4.4
             variables:
               USER: '$DEPLOY_USER'
               SERVER: '$DEPLOY_SERVER_EXP'
               REMOTE_PATH: '$DEPLOY_REMOTE_PATH'
               LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'

           - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
             variables:
               AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
               AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
               AWS_DEFAULT_REGION: us-west-2
               DISTRIBUTION_ID: 'E2JWMV46CT4WSG'



    stage:
      - step:                        # Stage deploy
         name: Deploy STAGE to new US site
         script:
           - echo $hardCodedOverrideConfig > app/js/Overridecore.js
           - sed -i -e  "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" -e "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" -e "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" app/js/Overridecore.js
           - tail -n +2 app/js/core.js >> app/js/Overridecore.js
           - mv app/js/Overridecore.js app/js/core.js

           - pipe: atlassian/rsync-deploy:0.4.4
             variables:
               USER: '$DEPLOY_USER'
               SERVER: '$DEPLOY_SERVER_STAGE'
               REMOTE_PATH: '$DEPLOY_REMOTE_PATH'
               LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'

           - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
             variables:
               AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
               AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
               AWS_DEFAULT_REGION: us-west-2
               DISTRIBUTION_ID: 'E3348D9PQPJA7J'



  custom:
    deployment-to-Stable-Manual: # Another display name
    - step:                        # Prod deploy
       name: Deploy STABLE to new US site server MANUALY
       deployment: stable
       script:
         - echo $hardCodedOverrideConfig > app/js/Overridecore.js
         - sed -i -e  "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" -e "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" -e "s/%BITBUCKET_BUILD_NUMBER%/$BITBUCKET_BUILD_NUMBER/" app/js/Overridecore.js
         - tail -n +2 app/js/core.js >> app/js/Overridecore.js
         - mv app/js/Overridecore.js app/js/core.js


         - pipe: atlassian/rsync-deploy:0.4.4
           variables:
             USER: '$DEPLOY_USER'
             SERVER: '$DEPLOY_SERVER_STABLE'
             REMOTE_PATH: '$DEPLOY_REMOTE_PATH'
             LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'

         - pipe: atlassian/aws-cloudfront-invalidate:0.5.0
           variables:
             AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
             AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
             AWS_DEFAULT_REGION: us-west-2
             DISTRIBUTION_ID: 'E2Q6XXPMBCQSSE'
